### ISSUE TITLE
Add .env to gitignore

### ISSUE THREAD

**Issue by nejdetkadir** [esrasen9/react-e-commerce-app#1]
We must to add .env file to gitignore because it includes some secret informations. Then you can create a file named ".env.example" in the root directory and fill its contents as follows. 
````
REACT_APP_API_KEY = X
REACT_APP_AUTH_DOMAIN =X
REACT_APP_PROJECT_ID = X
REACT_APP_STORAGE_BUCKET =X
REACT_APP_MESSAGING_SENDER_ID = X
REACT_APP_APP_ID = X
````

**Comment by esrasen9** [comment]
Thanks for the warning I updated my gitignore file.
